### ISSUE TITLE
Eliminacion Clase "PlanillaDeEntrega"

### ISSUE THREAD

**Issue by LucioB16** [Ciro-Rubiano/PPAI-DSI-3K3-GT-2018#10]
La planilla de entrega es un sumario de los remitos, es un documento de salida.
Ante la eliminación se quita del medio el problema de la **Triple Agregacion** que no sabiamos como quitarla, y a su vez se cierra un Circuito.
@Ciro-Rubiano @LucasMadrid estan de Acuerdo con esto

**Comment by Ciro-Rubiano** [comment]
Eliminado.
Solución de dependencias
