### ISSUE TITLE
Transaccion *Paciente* -- *Receta*

### ISSUE THREAD

**Issue by LucasMadrid** [Ciro-Rubiano/PPAI-DSI-3K3-GT-2018#2]
El patron participante --- transaccion.. no deberia, por ejemplo: que el paciente conozca la entrega?

**Comment by Ciro-Rubiano** [comment]
Ahi estoy viendo, Segun el Patrón 3º, El participante conoce a sus transacciones. De modo:
(paciente)[1]------>[0..*] (Entrega).

Ahora me fijo en el documento

**Comment by LucasMadrid** [comment]
Okey, entonces fijate la receta tambien que esta asi tipo.. receta conoce al paciente

**Comment by Ciro-Rubiano** [comment]
Vos decis de Incluir Una nueva relación (paciente)[1]------>[0..*] (Entrega).??

**Comment by LucasMadrid** [comment]
segun el patron, deberiamos ponerlo de esa manera.. que el paciente conozca la entreg. Y si lo aplicamos a la receta.. deberia ser paciente-------> receta. Pero no se si alguno piensa que no es asi

**Comment by Ciro-Rubiano** [comment]
El tema es que **receta** en si no es una transaccion como tal, sino que es el producto de una transaccion. La receta debe contener el nombre del paciente, por lo que la receta debe conocer al paciente. Por otro lado el patron deberia ser aplicado, pero no se si es Justo este patron el que se aplica.

**Comment by Ciro-Rubiano** [comment]
@Ciro-Rubiano En este caso la entrega si es una transacción por lo tanto el paciente debe conocer la entrega, pero para mi la receta no es una transacción, es la salida y como contiene el nombre del paciente la relación es receta conoce al paciente - byTamara

**Comment by Ciro-Rubiano** [comment]
Por Votacion:

`paciente`<----------`receta´
