### ISSUE TITLE
Relacion EntregaParcial -- Paciente

### ISSUE THREAD

**Issue by Ciro-Rubiano** [Ciro-Rubiano/PPAI-DSI-3K3-GT-2018#3]
Creo que la navegabilidad va en sentido contrario, es decir:
`paciente` --> `entregaParcial`. De esta Manera se respeta el Patron 3º.

La clase `EntregaParcial` tiene un atributo *paciente: Paciente*. Y no posee la relacion en ningun sentido.

**Comment by LucasMadrid** [comment]
sii cambialo
