### ISSUE TITLE
Cambiar Sentido de la navegabilidad entre las clases Receta y Paciente

### ISSUE THREAD

**Issue by LucioB16** [Ciro-Rubiano/PPAI-DSI-3K3-GT-2018#5]
Dado a lo que dijo @NelsonLoto sobre una consulta a la profe, el sentido de la navegabilidad es inversa a la actual. Hay que cambiar la relacion de modo que: `Paciente` ---> `Receta`. (Aplicar Patron 3) 
Puede convertise en un gran problema, hay que cambiar la estructura general del diagrama. 
Se recomienda no avanzar sobre las clases que dependan de `Receta` ni `Paciente`, ya que estas van a ser modificadas y por lo tanto su entorno tambien

**Comment by Ciro-Rubiano** [comment]
Solucionado @Francocasuscelli @LucasMadrid y Ciro
